export * from './contact-us'
export * from './why us'
export * from './section2'
export * from './serviceCard'
export * from './DynamicSection'
export * from './Dynamic Hero'
export * from './mini card'
export * from './paterns'
export * from './swiper'