import type { NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import { Navbar, Footer } from "@ui";
import {
  Contact_us,
  DynamicSection,
  Why_us,
  ServiceCard,
  DynamicHero,
} from "@components";
import { services } from "@constants";
import useTranslation from "next-translate/useTranslation";
const Section1_Images = [
  "/images/realestate/section1/1.png",
  "/images/realestate/section1/2.png",
  "/images/specialone/section1/3.png",
];
const hero_Images = [
  "/images/realestate/hero/1.png",
  "/images/realestate/hero/2.png",
  "/images/specialone/section1/3.png",
];
const Realestate: NextPage = () => {
  const { t, lang } = useTranslation("realestate");

  return (
    <>
      <Head>
        <title>Special One Company</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar logo="/images/real_estate_logo.svg" />
      <DynamicHero
        button={t("section1_button")}
        title="Real estate"
        title2={t("hero_title2")}
        description={t("hero_description")}
        images={hero_Images}
      />
      <DynamicSection
        images={Section1_Images}
        title={t("section1_title")}
        title2={t("section1_seconde_title")}
        description={t("section1_description")}
        button={t("section1_button")}
        lang={lang}
        id="to-element"
      />
      <div className="container ">
        <h5 className="text-[#f8bf58] text-center">
          {t("services_section_title")}
        </h5>
        <div className="flex flex-wrap flex-row justify-center gap-y-10 gap-x-20 px-4 my-20">
          {services?.map((item: any, index: number) => (
            <ServiceCard item={item} key={index} t={t} index={index} />
          ))}
        </div>
      </div>
      {/*<div className="container flex flex-wrap flex-row justify-center gap-y-10 gap-x-20 px-4 my-20">
        <div className="flex flex-col gap-y-4 max-w-[300px] w-[100%] zoom-div ">
          <div className="image-container">
            <img
              loading="lazy"
              src="/images/realestate/1.png"
              alt="image"
              className="zoom-image"
            />
          </div>

          <p className="text-[#d8ba71]">Villa in Ain Khaled</p>
        </div>
        <div className="flex flex-col gap-y-4 max-w-[300px] w-[100%] zoom-div">
          <div className="image-container">
            <img
              loading="lazy"
              src="/images/realestate/2.png"
              alt="image"
              className="zoom-image"
            />
          </div>
          <p className="text-[#d8ba71]">Lusail Townhouses</p>
        </div>
        <div className="flex flex-col gap-y-4 max-w-[300px] w-[100%] zoom-div">
          <div className="image-container">
            <img
              loading="lazy"
              src="/images/realestate/3.png"
              alt="image"
              className="zoom-image"
            />
          </div>
          <p className="text-[#d8ba71]">Al Thumama Villas</p>
        </div>
      </div>*/}

      <Why_us
        title={t("why_title")}
        title2={t("why_title2")}
        image="/images/realestate/why-us.png"
      >
        <ul className="list-disc mt-6">
          <li>{t("why_list_1")}</li>
          <li className="my-4">{t("why_list_2")}</li>
          <li>{t("why_list_3")}</li>
        </ul>
      </Why_us>
      <Contact_us t={t} />
      <Footer logo="/images/real_estate_logo.svg" />
    </>
  );
};

export default Realestate;
