import type { NextPage } from "next";
import Head from "next/head";
import { Navbar, Footer } from "@ui";
import {
  Contact_us,
  DynamicSection,
  Why_us,
  MiniCard,
  DynamicHero,
} from "@components";
import { Sparkling_services, Premium_Services } from "@constants";
import useTranslation from "next-translate/useTranslation";
const Section1_Images = [
  "/images/specialone/section1/1.png",
  "/images/specialone/section1/2.png",
  "/images/specialone/section1/3.png",
];
const Specialone: NextPage = () => {
  const { t, lang } = useTranslation("specialone");

  return (
    <>
      <Head>
        <title>Special One Company</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar logo="/images/special_one_logo.svg" />
      <DynamicHero
        button={t("section1_button")}
        title="special One"
        title2={t("hero_title2")}
        description={t("hero_description")}
        images={Section1_Images}
      />
      <DynamicSection
        images={Section1_Images}
        title={t("section1_title")}
        title2={t("section1_seconde_title")}
        description={t("section1_description")}
        button={t("section1_button")}
        lang={lang}
        id="to-element"
      />

      <div className="container px-4 my-20">
        <h4 className="text-[#f8bf58] text-center sm:px-4 ">
          {t("sparkling_services_title")}
        </h4>
        <div className="flex flex-wrap flex-row justify-center gap-y-10 gap-x-4 px-4 my-20">
          {Sparkling_services?.map((item: any, index: number) => (
            <MiniCard
              key={index}
              icon={item.icon}
              title={t(item.title)}
              index={index}
            />
          ))}
        </div>
      </div>

      <div className="relative py-[50px]">
        <img
          src="/images/shape.svg"
          className="absolute -left-[200px] -bottom-[200px] "
          style={{ zIndex: -1 }}
          loading="lazy"
        />
      </div>
      <div className="container px-4 my-20">
        <h4 className="text-[#f8bf58] text-center sm:px-4 ">
          {t("premium_services_title")}
        </h4>
        <div className="flex flex-wrap flex-row justify-center gap-y-10 gap-x-4 px-4 my-20">
          {Premium_Services?.map((item: any, index: number) => (
            <MiniCard
              key={index}
              icon={item.icon}
              title={t(item.title)}
              index={index}
            />
          ))}
        </div>
      </div>

      <div className="container px-4 flex flex-col items-center my-40">
        <h3 className="text-[#f8bf58] text-center">{t("Partner_title")}</h3>
        <div className="relative py-8 px-4 shadow-lg my-8 max-w-[800px] m-auto ">
          <div className="p-6 bg-[#fff6e7]">
            <p className="text-center">{t("Partner_description")}</p>
          </div>
        </div>
        <img src="/images/shape.svg" alt="" />
      </div>
      <Why_us
        title={t("why_title")}
        title2={t("why_title2")}
        image="/images/specialone/why_us.png"
      >
        <p>{t("why_description")}</p>
      </Why_us>
      <Contact_us t={t} />
      <Footer logo="/images/special_one_logo.svg" />
    </>
  );
};

export default Specialone;
